[package]
name = "huttp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
listenfd = "1.0.2"
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
